In [1]:
import pandas as pd
import os
import re

In [2]:
folders = os.listdir("ALL_STOCKMARKET_DATA_2020_24/IT_SECTOR_2020_24")
folders.remove('.DS_Store')
folders

['COMMUNICATIONS_EQUIPMENT',
 'CONSUMER_ELECTRONICS',
 'DATA_PROCESSING',
 'ELECTRONIC_EQUIPMENT',
 'INTERNET_SERVICES',
 'IT_SERVICES',
 'SEMICONDUCTORS',
 'SOFTWARE',
 'TECHNOLOGY_HARDWARE']

In [3]:
all_year_data = pd.DataFrame()

for folder in folders:
    #print(folder)
    # loop through years
    for year in range(2020, 2025):
        #print(year)
        files = os.listdir(f"ALL_STOCKMARKET_DATA_2020_24/IT_SECTOR_2020_24/{folder}/{year}")
        #print(files)
        # load each file
        for file in files:
            data = pd.read_csv(f"ALL_STOCKMARKET_DATA_2020_24/IT_SECTOR_2020_24/{folder}/{year}/{file}")
            ticker_name = re.findall('(\w*)_\d{4}\.csv', file)[0]
            data = data.assign(Ticker=ticker_name)
            all_year_data = pd.concat([all_year_data, data])

all_year_data

,Unnamed: 0,Open,High,Low,Close,Adjusted Close,Volume,Dividend Amount,Split Coefficient,Index,Ticker
0,2020-01-02,205.68,207.235,203.10,204.72,51.1800,624527,0.0,1.0,Communications_Equipment,ANET
1,2020-01-03,200.00,203.830,198.48,200.85,50.2125,766873,0.0,1.0,Communications_Equipment,ANET
2,2020-01-06,198.79,203.170,198.00,202.86,50.7150,516039,0.0,1.0,Communications_Equipment,ANET
3,2020-01-07,202.86,205.430,201.30,204.85,51.2125,532930,0.0,1.0,Communications_Equipment,ANET
4,2020-01-08,204.85,207.790,204.63,206.98,51.7450,673786,0.0,1.0,Communications_Equipment,ANET
...,...,...,...,...,...,...,...,...,...,...,...
161,2024-08-22,64.79,65.490,63.85,64.04,64.0400,3177693,0.0,1.0,Technology_Hardware,WDC
162,2024-08-23,64.25,65.035,63.45,64.35,64.3500,3045446,0.0,1.0,Technology_Hardware,WDC
163,2024-08-26,63.89,64.290,62.43,62.69,62.6900,3247198,0.0,1.0,Technology_Hardware,WDC
164,2024-08-27,61.83,63.100,61.16,62.85,62.8500,5045809,0.0,1.0,Technology_Hardware,WDC
165,2024-08-28,62.21,62.710,61.11,62.43,62.4300,4673061,0.0,1.0,Technology_Hardware,WDC

In [4]:
all_year_data['Daily_Change_In_Price'] = (all_year_data['Close'] - all_year_data['Close'].shift(1)) / all_year_data['Close'].shift(1)
all_year_data

,Unnamed: 0,Open,High,Low,Close,Adjusted Close,Volume,Dividend Amount,Split Coefficient,Index,Ticker,Daily_Change_In_Price
0,2020-01-02,205.68,207.235,203.10,204.72,51.1800,624527,0.0,1.0,Communications_Equipment,ANET,NaN
1,2020-01-03,200.00,203.830,198.48,200.85,50.2125,766873,0.0,1.0,Communications_Equipment,ANET,-0.018904
2,2020-01-06,198.79,203.170,198.00,202.86,50.7150,516039,0.0,1.0,Communications_Equipment,ANET,0.010007
3,2020-01-07,202.86,205.430,201.30,204.85,51.2125,532930,0.0,1.0,Communications_Equipment,ANET,0.009810
4,2020-01-08,204.85,207.790,204.63,206.98,51.7450,673786,0.0,1.0,Communications_Equipment,ANET,0.010398
...,...,...,...,...,...,...,...,...,...,...,...,...
161,2024-08-22,64.79,65.490,63.85,64.04,64.0400,3177693,0.0,1.0,Technology_Hardware,WDC,-0.015224
162,2024-08-23,64.25,65.035,63.45,64.35,64.3500,3045446,0.0,1.0,Technology_Hardware,WDC,0.004841
163,2024-08-26,63.89,64.290,62.43,62.69,62.6900,3247198,0.0,1.0,Technology_Hardware,WDC,-0.025796
164,2024-08-27,61.83,63.100,61.16,62.85,62.8500,5045809,0.0,1.0,Technology_Hardware,WDC,0.002552
165,2024-08-28,62.21,62.710,61.11,62.43,62.4300,4673061,0.0,1.0,Technology_Hardware,WDC,-0.006683

In [5]:
all_year_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 38677 entries, 0 to 165
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             38677 non-null  object
 1   Open                   38677 non-null  float64
 2   High                   38677 non-null  float64
 3   Low                    38677 non-null  float64
 4   Close                  38677 non-null  float64
 5   Adjusted Close         38677 non-null  float64
 6   Volume                 38677 non-null  int64
 7   Dividend Amount        38677 non-null  float64
 8   Split Coefficient      38677 non-null  float64
 9   Index                  38677 non-null  object
 10  Ticker                 38677 non-null  object
 11  Daily_Change_In_Price  38676 non-null  float64
dtypes: float64(8), int64(1), object(3)
memory usage: 3.8+ MB

In [6]:
all_year_data['Unnamed: 0'] = pd.to_datetime(all_year_data['Unnamed: 0'])
all_year_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 38677 entries, 0 to 165
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             38677 non-null  datetime64[ns]
 1   Open                   38677 non-null  float64
 2   High                   38677 non-null  float64
 3   Low                    38677 non-null  float64
 4   Close                  38677 non-null  float64
 5   Adjusted Close         38677 non-null  float64
 6   Volume                 38677 non-null  int64
 7   Dividend Amount        38677 non-null  float64
 8   Split Coefficient      38677 non-null  float64
 9   Index                  38677 non-null  object
 10  Ticker                 38677 non-null  object
 11  Daily_Change_In_Price  38676 non-null  float64
dtypes: datetime64[ns](1), float64(8), int64(1), object(2)
memory usage: 3.8+ MB

In [7]:
all_year_data.rename(columns={"Unnamed: 0": "date"}, inplace=True)
all_year_data = all_year_data.sort_values(by='date')
all_year_data['MA_5'] = all_year_data['Close'].rolling(window=5).mean().shift(1)
all_year_data = all_year_data.dropna(subset=['MA_5'])
all_year_data

,date,Open,High,Low,Close,Adjusted Close,Volume,Dividend Amount,Split Coefficient,Index,Ticker,Daily_Change_In_Price,MA_5
0,2020-01-02,296.24,300.60,295.1900,300.35,72.877480,33911864,0.0,1.0,Consumer_Electronics,AAPL,6.736991,128.754
0,2020-01-02,97.62,98.47,97.3800,98.34,88.094559,828006,0.0,1.0,Consumer_Electronics,GRMN,-0.258874,147.880
0,2020-01-02,68.30,69.06,68.2800,69.06,68.336220,856522,0.0,1.0,Consumer_Electronics,SNE,-0.422865,154.424
0,2020-01-02,53.27,53.96,53.2300,53.95,50.079683,13899603,0.0,1.0,Software,ORCL,-0.757441,164.078
0,2020-01-02,158.78,160.73,158.3300,160.62,153.931071,22634546,0.0,1.0,Software,MSFT,-0.577149,164.410
...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,2024-08-28,50.45,50.57,49.4100,49.85,49.850000,14571378,0.0,1.0,Communications_Equipment,CSCO,-0.016959,315.956
165,2024-08-28,173.69,173.69,168.9200,170.80,170.800000,29045025,0.0,1.0,Internet_Services,AMZN,-0.013401,310.552
165,2024-08-28,42.55,42.60,42.0245,42.32,42.320000,3727111,0.0,1.0,Electronic_Equipment,GLW,-0.004704,221.304
165,2024-08-28,154.10,154.64,151.7300,152.59,152.590000,752366,0.0,1.0,Electronic_Equipment,KEYS,-0.009799,162.290
165,2024-08-28,62.21,62.71,61.1100,62.43,62.430000,4673061,0.0,1.0,Technology_Hardware,WDC,-0.006683,110.688

In [8]:
all_year_data['Binary_Returns'] = all_year_data['Daily_Change_In_Price'].apply(lambda x: 1 if x > 0 else 0)

In [11]:
all_year_data.sort_values(["Ticker","date"])

,date,Open,High,Low,Close,Adjusted Close,Volume,Dividend Amount,Split Coefficient,Index,Ticker,Daily_Change_In_Price,MA_5,Binary_Returns
0,2020-01-02,296.24,300.600,295.19,300.35,72.877480,33911864,0.0,1.0,Consumer_Electronics,AAPL,6.736991,128.754,1
1,2020-01-03,297.15,300.580,296.50,297.43,72.168966,36633878,0.0,1.0,Technology_Hardware,AAPL,-0.009722,109.562,0
1,2020-01-03,297.15,300.580,296.50,297.43,72.168966,36633878,0.0,1.0,Consumer_Electronics,AAPL,-0.009722,164.942,0
2,2020-01-06,293.79,299.960,292.75,299.80,72.744027,29644644,0.0,1.0,Technology_Hardware,AAPL,0.007968,418.048,1
2,2020-01-06,293.79,299.960,292.75,299.80,72.744027,29644644,0.0,1.0,Consumer_Electronics,AAPL,0.007968,208.914,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,2024-08-22,64.79,65.490,63.85,64.04,64.040000,3177693,0.0,1.0,Technology_Hardware,WDC,-0.015224,167.102,0
162,2024-08-23,64.25,65.035,63.45,64.35,64.350000,3045446,0.0,1.0,Technology_Hardware,WDC,0.004841,177.934,1
163,2024-08-26,63.89,64.290,62.43,62.69,62.690000,3247198,0.0,1.0,Technology_Hardware,WDC,-0.025796,280.264,0
164,2024-08-27,61.83,63.100,61.16,62.85,62.850000,5045809,0.0,1.0,Technology_Hardware,WDC,0.002552,282.346,1
165,2024-08-28,62.21,62.710,61.11,62.43,62.430000,4673061,0.0,1.0,Technology_Hardware,WDC,-0.006683,110.688,0